<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxrTIdv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxrTIdv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxrTIdv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxrTIdv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxrTIdv\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxrTIdv',
    'container.build_id' => '05453273',
    'container.build_time' => 1646576881,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxrTIdv');
