<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFDmwOVx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFDmwOVx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFDmwOVx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFDmwOVx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFDmwOVx\App_KernelDevDebugContainer([
    'container.build_hash' => 'FDmwOVx',
    'container.build_id' => '6be2667a',
    'container.build_time' => 1645900520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFDmwOVx');
