<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ1tMxx5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ1tMxx5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ1tMxx5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ1tMxx5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ1tMxx5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q1tMxx5',
    'container.build_id' => '8cf43799',
    'container.build_time' => 1648414185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ1tMxx5');
