<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEsDXWVF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEsDXWVF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEsDXWVF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEsDXWVF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEsDXWVF\App_KernelDevDebugContainer([
    'container.build_hash' => 'EsDXWVF',
    'container.build_id' => 'fe642a74',
    'container.build_time' => 1650635751,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEsDXWVF');
