<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHKkIMWV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHKkIMWV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHKkIMWV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHKkIMWV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHKkIMWV\App_KernelDevDebugContainer([
    'container.build_hash' => 'HKkIMWV',
    'container.build_id' => 'a5f6d9f5',
    'container.build_time' => 1650731331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHKkIMWV');
