<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNFPgb3L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNFPgb3L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNFPgb3L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNFPgb3L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNFPgb3L\App_KernelDevDebugContainer([
    'container.build_hash' => 'NFPgb3L',
    'container.build_id' => 'dd4283f7',
    'container.build_time' => 1649005453,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNFPgb3L');
